services:
  service-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/autoBot:/var/autoBot
    ports:
      - "8080:8080"
    environment:
      - TOKEN_BOT=${BOT_TOKEN}
      - KOSVLAS=${KOSVLAS}
    env_file:
      - /etc/autoBot/.prod_env

# add here .prod_env to load ENVIRONMENT = production